### ISSUE TITLE
IllegalStateException when navigating with the arrow buttons

### ISSUE THREAD

**Issue by jarrah42** [bssw-psip/psip-automation#10]
I'm seeing the following in the log. It's occurring when the MainLayout#navigate method is calling setVisible on the NavItem.

Jul 24 08:07:21 ip-172-31-42-220 web: 2020-07-24 08:07:21.763 ERROR 27890 --- [nio-5000-exec-1] io.bssw.psip.ui.MainLayout               : Uncaught UI exception
Jul 24 08:07:21 ip-172-31-42-220 web: java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:535) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:549) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:408) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.StateTree.markAsDirty(StateTree.java:279) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.StateNode.markAsDirty(StateNode.java:558) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.NodeMap.setChanged(NodeMap.java:383) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.NodeMap.put(NodeMap.java:195) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.NodeMap.put(NodeMap.java:172) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.ElementData.setVisible(ElementData.java:80) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.dom.impl.BasicElementStateProvider.setVisible(BasicElementStateProvider.java:390) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.dom.Element.setVisible(Element.java:1466) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.component.Component.setVisible(Component.java:535) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at io.bssw.psip.ui.components.navigation.drawer.NaviItem.setVisible(NaviItem.java:184) ~[classes!/:1.0-SNAPSHOT]
Jul 24 08:07:21 ip-172-31-42-220 web: at io.bssw.psip.ui.MainLayout.navigate(MainLayout.java:328) ~[classes!/:1.0-SNAPSHOT]
Jul 24 08:07:21 ip-172-31-42-220 web: at io.bssw.psip.ui.views.Assessment.lambda$createItemLayout$19d300e3$1(Assessment.java:132) ~[classes!/:1.0-SNAPSHOT]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:441) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:441) ~[flow-server-3.1.2.jar!/:3.1.2]
Jul 24 08:07:21 ip-172-31-42-220 web: at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59) ~[flow-server-3.1.2.jar!/:3.1.2]

**Comment by jarrah42** [comment]
Applies to legacy UI, ongoing work will focus on new UI.
